import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-black dark:bg-neutral-900 dark:text-white flex flex-col items-center justify-start min-h-dvh h-full antialiased p-6">
        <div className="container w-full">{children}</div>
      </body>
    </html>
  );
}
